language: ruby
rvm:
  - 2.5.1

before_script:
- chmod +x ./script/cibuild

script: ./script/cibuild
dist: trusty
cache: bundler

env:
   global:
   - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  provider: surge
  skip_cleanup: true
  project: ./_site/
  domain: https://yaswanth.surge.sh
on:
  branch: master
