language: ruby
rvm:
  - 2.5.1

before_script:
- chmod +x ./script/cibuild

script: ./script/cibuild

cache: bundler

deploy:
  provider: surge
  skip_cleanup: true
  project: ./_site/
  domain: https://yaswanth.surge.sh
on:
  branch: master