# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate, jekyll-feed]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://yashwanth2804.github.io/
baseurl: ""
title: Yaswanth Kambala
author: Yaswanth Kambala
description: Personal blog and resume
avatar: yash.jpg
email: kambaalayashwanth@outlook.com
github: yashwanth2804 # username
twitter: yasheinstein2
linkedin: yashwanth-kambala-2a2b5626 #yaswanth-kambala-2a2b5626
stackoverflow: users/3453912/yashwanthkambala #e.g: users/2735833/proton1h1
tel: +91-7396873676
tel_full: tel:+91-7396873676
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1

# needed for travis-ci build
exclude: [vendor, node_modules]
